* DONE 1й уровень -- connection
  + app, sup
    + connection_pool_sup
      + connection_sup (register with ConnectionName, run Num connection_worker)
  + динамическое создание новых соединений и остановка их
    для каждого {ConnectionName, #amqp_network_params{}} нужно создать connection_sup
    и под ним несколько connection_worker
  + connect
  + reconnect
  + close connection
  + monitor connection

* 2й уровень -- channel
  + channel_sup (simple_one_for_one), run channel_worker
  - создание channel и channel_worker по требованию
    + по ConnectionName выбрать нужный connection_sup
    + для этого sup обойти все его connection_worker
      и выбрать тот, у кого меньше всего channel
    - connection_worker вызывает
      fox_channel_sup:start_channel(self(), 42),
      - какие аргументы передать?
        amqp_connection:open_channel(ConnectionPid, ChannelNumber, {_ConsumerModule, _ConsumerArgs} = Consumer) ->
        - что такое ChannelNumber?
        - разобраться с Consumer
          The consumer module for a channel is chosen when the channel is opened by
          setting the second parameter to amqp_connection:open_channel/2. The
          consumer module implements the amqp_gen_consumer behaviour and thus
          implements functions to handle receiving basic.consume,
          basic.consume_ok, basic.cancel, basic.cancel_ok methods as well as publishes.
  - хранить их внутри connection_worker
  - завершение channel_worker

** АПИ 2-го уровня:
  - create_channel(ConnectionName) -> ChannelPid
  - close_channel(ConnectionName, ChannelPid) -> ok

* 3й уровень -- сценарии использования channel
  channel_worker хранит внутри себя channel (свой собственный, экслюзивный)
  и предоставляет АПИ для основных сценариев:
  - publish (async)
  - publish with confirmation (не документарован, нужно разбираться)
  - declare exchange, declare queue, bind queue
  - subscribe
    behaviour amqp_subscriber (придумать название)
    - init(ChannelPid) -> State. Тут делать все declare и bind
    - handle_message(Message, ChannelPid, State)
    sample_subscriber модуль, включить в либу, использовать в тестах
  - unsubscribe
  сделаю везде мапы как альтернативу рекордам

** АПИ 3-го уровня нужно продумать:
  - publish(ChannelPid, Data) ?
  - publish_with_confirmation?
    https://www.rabbitmq.com/confirms.html
  - subscribe(ChannelPid, callback, #amqp_consumer{}) ?
    behaviour amqp_consumer
    process_data(ChannelPid, Data) -> ack | reject
    unsubscribe() ?
  - declare exchange, queue, bind

* Мониторинг:
  - connection_worker должен мониторить channel и channel_worker
    перезапускать их, если они упали, заново объявлять и связывать, если нужно
  - connection_worker после reconnect должен создать новые channel и раздать их channel_worker
    ну и те должны заново инициализироваться

* README
документация на весь АПИ
- fox:create_channel/1 -- за канал отвечает потребитель, либа дальше этот канал не использует и не мониторит
как работает либа (структура потоков и т.д.)

* samples

* info
http://www.rabbitmq.com/erlang-client-user-guide.html
https://www.rabbitmq.com/confirms.html
